Добавлена страница проекта
keksec-team/molva-frontend pull request #8
Opened 2020-10-18 17:30 UTC by iamnzrv

2020-10-23 13:59 UTC, corradowaver requested changes

2020-10-23 13:59 UTC, corradowaver commented on src/component/app/main/project/Project.js
> +        // fetch(`https://api.example.com/projects/${props.projectId}`)
Who eto?

2020-10-23 13:59 UTC, corradowaver commented on src/component/app/main/project/helper/helper.js
> +}
eof

2020-10-23 13:59 UTC, corradowaver commented on src/component/app/main/projects/Projects.js
> +        // fetch(`https://api.example.com/projects/by/category/${currentActiveCategory}`)
who eta?

2020-10-23 13:59 UTC, corradowaver commented on src/resources/categories.js
> +export let categories = ["apps", "sites", "games", "films"]
eof

2020-10-23 13:59 UTC, corradowaver commented on src/component/app/main/projects/preview/Preview.module.css
>  }
eof

2020-10-23 13:59 UTC, corradowaver commented on src/service/fakeDataService.js
>  }
eof

2020-10-23 13:59 UTC, corradowaver commented on src/service/fakeDataSource.js
> +}
eof

2020-10-23 13:59 UTC, corradowaver commented on src/component/app/main/project/Project.module.css
> +}
eof

2020-10-23 13:59 UTC, corradowaver commented on src/component/app/helper/LoadingIndicator.module.css
> +}
eof

2020-10-23 13:59 UTC, corradowaver commented on src/component/app/main/projects/categories/Categories.js
> +    let categories = {"apps": strings.appsCategory, "sites": strings.sitesCategory, "games": strings.gamesCategory, "films": strings.filmsCategory}
beggar categories class

2020-10-23 13:59 UTC, corradowaver commented on src/component/app/main/projects/preview/Preview.js
> +            isLink ? <Link to={{pathname: "project", state: {activeId}}}>
hardcoded spook

2020-10-23 14:32 UTC, iamnzrv commented on src/component/app/main/project/Project.js
> +        // fetch(`https://api.example.com/projects/${props.projectId}`)
Запрос...оставил для примера, чтобы потом можно было просто вставить наш url

2020-10-23 14:32 UTC, iamnzrv commented on src/component/app/main/project/helper/helper.js
> +}
-_-

2020-10-23 14:33 UTC, iamnzrv commented on src/component/app/main/projects/Projects.js
> +        // fetch(`https://api.example.com/projects/by/category/${currentActiveCategory}`)
Выше есть

2020-10-23 14:33 UTC, iamnzrv commented on src/resources/categories.js
> +export let categories = ["apps", "sites", "games", "films"]
-_-

2020-10-23 14:33 UTC, iamnzrv commented on src/component/app/main/projects/preview/Preview.module.css
>  }
-_-

2020-10-23 15:01 UTC, corradowaver commented on src/component/app/main/projects/categories/Categories.js
> +    let categories = {"apps": strings.appsCategory, "sites": strings.sitesCategory, "games": strings.gamesCategory, "films": strings.filmsCategory}
а когда он станет крутым то

2020-10-23 16:23 UTC, corradowaver requested changes

2020-10-23 16:23 UTC, corradowaver commented on src/component/app/main/projects/preview/Preview.js
> +            isLink ? <Link to={{pathname: pages.PROJECT, state: {activeId}}}>
Я хочю использовать превью в крейторах мне не нужны прожекты блин(

2020-10-23 16:23 UTC, corradowaver commented on src/component/app/main/projects/preview/Preview.js
> +            isLink ? <Link to={{pathname: pages.PROJECT, state: {activeId}}}>
в пропсы хочю!

2020-10-24 09:00 UTC, corradowaver approved these changes
Ai oi ui oe хорошая работа. Олег.

2020-10-24 09:01 UTC, merged